In [1]:
#1D numpy array
import numpy as np

In [2]:
#create array from 1to 20
arr = np.arange(1, 21)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
#Calculations
total_sum = np.sum(arr)
mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev = np.std(arr)

In [12]:
print("Sum:", total_sum)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [7]:
#find indices where element is greater than 10
indices = np.where(arr>10)

In [8]:
print("indices of the elements greter than 10", indices[0])

indices of the elements greter than 10 [10 11 12 13 14 15 16 17 18 19]


In [9]:
#Create 2D array of shape (4, 4)
arr_2D = np.arange(1, 17).reshape(4, 4)

In [10]:
#print the array
arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
#find the transpose
import numpy as np
arr_2D = np.arange(1, 17).reshape(4, 4)
transpose_array = arr_2D.T

In [7]:
#print transpose
print("Original Array:\n", arr_2D)
print("\nTranspose of Array:\n", transpose_array)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [8]:
#Calculate the row-wise and Column-wise sums of the array 
import numpy as np

In [9]:
arr_2D = np.arange(1, 17).reshape(4, 4)

In [11]:
#Row-wise Sum
row_sum = np.sum(arr_2D, axis = 1)

In [12]:
#Column-wise Sum
col_sum = np.sum(arr_2D, axis = 0)

In [14]:
#print result
print("Array:\n",arr_2D)
print("\nRow-wise sum:",row_sum)
print("Column-wise sum:",col_sum)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


In [15]:
#Create two 3 X 3 arrays filled with random integers between 1 and 20.
import numpy as np

In [18]:
array1 = np.random.randint(1, 21, size =(3, 3))
array2 = np.random.randint(1, 21, size =(3, 3))

In [22]:
print("Array:\n",array1)
print("\nArray:\n",array2)

Array:
 [[13  7  5]
 [ 5 14  4]
 [ 9 19 11]]

Array:
 [[ 8 20 20]
 [19 15 16]
 [17  5  2]]


In [24]:
#perform element-wise addition, subtraction, and multiplication
array1 = np.random.randint(1, 21, size =(3, 3))
array2 = np.random.randint(1, 21, size =(3, 3))

In [26]:
#Element-wise Operation
addition = array1 + array2
substraction = array1 - array2
multiplication = array1 * array2

In [28]:
#print result 
print("Array:\n",array1)
print("\nArray:\n",array2)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise substraction:\n", substraction)
print("\nElement-wise Multtiplication:\n", multiplication)

Array:
 [[15  5 10]
 [ 3 18 10]
 [ 2 17  6]]

Array:
 [[ 2 16 11]
 [ 4 11  8]
 [15 14 16]]

Element-wise Addition:
 [[17 21 21]
 [ 7 29 18]
 [17 31 22]]

Element-wise substraction:
 [[ 13 -11  -1]
 [ -1   7   2]
 [-13   3 -10]]

Element-wise Multtiplication:
 [[ 30  80 110]
 [ 12 198  80]
 [ 30 238  96]]


In [29]:
#compute the dot product of the two arrays
array1 = np.random.randint(1, 21, size =(3, 3))
array2 = np.random.randint(1, 21, size =(3, 3))

In [30]:
dot_product = np.dot(array1, array2)

In [33]:
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nDot Product (Matrix Multiplication):\n", dot_product)

Array 1:
 [[12  6  1]
 [10  1 16]
 [ 9  8 12]]

Array 2:
 [[16  5  2]
 [10 10 19]
 [10  7 11]]

Dot Product (Matrix Multiplication):
 [[262 127 149]
 [330 172 215]
 [344 209 302]]


In [34]:
#create 1D array of size 12
arr_1D = np.arange(1, 13

In [36]:
#Reshape array 
arr_2D = arr_1D.reshape(3, 4)

In [37]:
#sliced first two rows (0:2) and Last two columns -2
sliced_array = arr_2D[0:2, -2:]

In [39]:
print("Original 1D Array:\n", arr_1D)
print("\nReshaped 3x4 Array:\n", arr_2D)
print("\nSliced (First 2 rows, Last 2 columns):\n", sliced_array)

Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced (First 2 rows, Last 2 columns):
 [[3 4]
 [7 8]]
